language: php

php:
    - 5.5
    - 5.6
    - 7
  
install:
    - composer install --prefer-source
    - vendor/bin/phpunit -coverage-clover ./build/logs/clover.xml
  
script:
    - vendor/bin/php-cs-fixer fix -v --dry-run ./test

after_script:
  - php vendor/bin/coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml
